name: Automatic executions of actions

on:
  push:
    
  pull_request:
    branches:
    - main

jobs:
  commit:
    runs-on: ubuntu-latest
    name: commit
    steps:
      - run:
          npm install
          npm run lint:js
          npm run lint:css
          npm run start
          echo "линтеры отработали и билд запустился"
  merge:
    name: merge
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm install
          npm run build
          npm run deploy
          echo "деплой готов"
  
