name: Automatic executions of actions

on:
  push:
    
  pull_request:
    branches:
    - master

jobs:
  commit:
    runs-on: ubuntu-latest
    name: commit
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: build dep
        run: npm install

      - name: fix js
        run: npx eslint --fix "src/*.js"

      - name: fix css
        run: npx stylelint --fix "src/*.css"

      - name: run lint:js
        run: npm run lint:js
      
      - name: run lint:css
        run: npm run lint:css
      
      - name: final build
        run: npm run build
      
      - name: result
        run: echo "линтеры отработали и билд запустился"

  merge:
    name: merge
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: build dep
        run: npm ci
      
      - name: build
        run: npm run build
      
      - name: deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      - env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: result
        run: echo "деплой готов"
  
