name: Automatic executions of actions

on:
  push:
    
  pull_request:
    branches:
    - main

jobs:
  commit:
    runs-on: ubuntu-latest
    name: commit
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: build dep
        run: npm install
      
      - name: run
        run: npm run
      
      - name: result
        run: echo "линтеры отработали и билд запустился"

  merge:
    name: merge
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - run: |
          npm install
          npm run build
          npm run deploy
          echo "деплой готов"
  
