name: Automatic executions of actions

on:
  push:
    branches:
    - main
  pull_request:
    - main

jobs:
  Commit:
      run: |
      npm install
      npm run lint:js
      npm run lint:css
      npm run start
      echo "линтеры отработали и билд запустился"
  Merge:
    run: |
        npm install
        npm run build
        npm run deploy
        echo "деплой готов"
  
